### ISSUE TITLE
Compare target is not called from main Makefile

### ISSUE THREAD

**Issue by maierbn** [cbm-software/iron-tests#19]
A call to the top-level  `make` fails in `create-figures` because the `results/failed.tests` and `results/results.summary` files do not yet exists. Remedy is to call the `compare` targets first.

**Comment by beauof** [comment]
`make compare` only works (and only makes sense) if all tests were run beforehand.

Also the `create-figures` target should not have anything to do with the test summary files?

**Comment by maierbn** [comment]
If you run `make` I would assume that it compiles everything, runs all tests, compares them, creates the pdf document. The default target is currently:

```
default:
	make clean
	make run-tests-release
	make collect-results
	make create-figures
	make latexmk
```
This fails in `make collect-results`, which is: 

```
collect-results:
	cd examples; bash collect_results.sh
```

Because the tests were not evaluated/compared earlier. There should also be a top-level compare target with the content
`cd examples && bash run_examples.sh compare`

**Comment by maierbn** [comment]
By the way I failed with my pull-request, it contains parts of the other issue #15 .

**Comment by beauof** [comment]
You're right about calling the compare targets beforehand from the examples/ directory.
I found the error when I looked at pull-request #20 and left a comment.
